version: '3.9'

services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: onjin/alpine-postgres:9.5
    environment:
      POSTGRES_USER: hellofresh
      POSTGRES_PASSWORD: hellofresh
      POSTGRES_DB: hellofresh
    ports:
      - "5432:5432"

  redis:
    image: sickp/alpine-redis:3.2.2
    ports:
      - "6379:6379"
